apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-base
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
  description: Base cluster configuration
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/mnlawler/gitops.git'