apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- operator/grafana-subscription.yaml
- operator/namespace.yaml
- operator/operator-group.yaml
- instance/ca-configmap.yaml
- instance/cluster-monitoring-config.yaml
- instance/session-secret.yaml
- instance/grafana-proxy-rbac.yaml
- instance/grafana.yaml
- instance/grafana-ds.yaml
- instance/patch-grafana-ds-sa.yaml
- instance/patch-grafana-ds-job.yaml
- instance/cluster-monitor-view-rb.yaml